### ISSUE TITLE
Meta : Game with Texture Stretching

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1034]
### Bug Description

Some games have Texture stretching on some objects
### Games Affected
[Rugby 2006](https://xemu.app/titles/45410087/#Rugby-06)
![xemu-2022-06-24-22-16-07](https://user-images.githubusercontent.com/71127352/175772138-8bd373cc-2c0e-460f-834e-1d1654a57f54.png)
[Charlie and the chocolate factory ](https://xemu.app/titles/54540081/#Charlie-and-the-Chocolate-Factory)
![image](https://user-images.githubusercontent.com/71127352/172951232-a5a66db7-9079-4fc6-bbec-ec48d71cc2d5.png)
[Shenmue II](https://xemu.app/titles/4d530032/#Shenmue-II) #988
[~~F1 Career Challenge~~ Unrelated](https://xemu.app/titles/45410032/#F1-Career-Challenge)
[Men of Valor](https://xemu.app/titles/56550019/#Men-of-Valor)
### Expected Behavior

Should not stretch

### xemu Version

Version: 0.7.28
Branch: master
Commit:https://github.com/mborgerson/xemu/commit/176b574403e0f4a08bfb1f8ab58e0f819a45cf81
Date: Fri Jun 3 21:40:57 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

**Comment by abaire** [comment]
The screenshot for Charlie... looks like a texture that's been set to clamp instead of repeat.

UPDATE:
The brick texture is `NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT23_A8R8G8B8`, looks fine in renderdoc at all 3 of the mip levels (mip mapping stopps at 32x32). As anticipated, the wrap mode is set to ST: ClampEdge, R:Repeat which seems clearly wrong for this usage.

The pgraph behavior is very unusual, there are a huge number of NOP instructions between a series of draws that use this texture. For the draw that first sets up the texture (the draw that renders the ground is a few after this, but there are no changes to the texture settings in between) the texture address mode is explicitly set to `Clamp_Edge`, which seems odd, but TEXGEN is also set to `NV097_SET_TEXGEN_S_REFLECTION_MAP` for S, T, and R . 

UPDATE: Actually looking more carefully at the full chain of draws using this texture, several are made with `NV097_SET_TEXTURE_ADDRESS` set to ClampEdge, but it's set to `Wrap` before the draw of the ground. This is not reflected in renderdoc, which appears to be the problem.

Confirmed that that is the problem. The texture is created and initialized in ClampEdge mode, and when the address mode is set to Wrap, xemu exits early before applying the change when it sees that the texture contents are unchanged: https://github.com/mborgerson/xemu/blob/master/hw/xbox/nv2a/pgraph.c#L6587.

**Comment by abaire** [comment]
@Triticum0 can you see if PR #1170 fixes Rugby 2006? I only have Charlie and the Chocolate Factory.

**Comment by Triticum0** [comment]
@abaire I Tested all the games on the list and it fixed all of them except for [F1 Career Challenge](https://xemu.app/titles/45410032/#F1-Career-Challenge) which is unrelated to this issue. The Issue In [F1 Career Challenge](https://xemu.app/titles/45410032/#F1-Career-Challenge) is a pixel rounding issue and is fixed by #735 also a shadow issue.

**Comment by Triticum0** [comment]
So you can close this issue once the pr merged
