### ISSUE TITLE
NV2A_VERTEX_ATTR_* constants are misleading / incorrect

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1037]
This table is probably misleading / incorrect / useless:
https://github.com/mborgerson/xemu/blob/176b574403e0f4a08bfb1f8ab58e0f819a45cf81/hw/xbox/nv2a/nv2a_regs.h#L1398-L1413
The above order is the same that's used for the vertex-shader output registers:
https://github.com/mborgerson/xemu/blob/176b574403e0f4a08bfb1f8ab58e0f819a45cf81/hw/xbox/nv2a/vsh.c#L269-L286

However, I don't think it's useful to keep a macro for this as the code in nv2a.c will mostly deal with vertex input attributes.

For example, `NV2A_VERTEX_ATTR_TEXTURE0` should probably be 8 (input attribute) instead of 9 (output register).
Other attributes would be incorrect, too, if treated for input attribute indices.

For the more useful input indices, [see "Table X.3: The mapping between vertex attribute register numbers, mnemonics, and meanings." in NV_vertex_program.txt](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_program.txt).

This is not a problem at the moment: XQEMU only uses  `NV2A_VERTEX_ATTR_POSITION`(0 eitherway) and `NV2A_VERTEX_ATTR_DIFFUSE `(3 eitherway + only used in comment).
However, both are used to describe vertex input attributes (`pg->vertex_attributes[]`).

### Additional Context

This was ripped directly from https://github.com/xqemu/xqemu/issues/258 So big thanks to JayFoxRox for the information.

**Comment by Triticum0** [comment]
>I just noticed that the inputs to the fixed-function pipeline are also the same as in nv2a_regs.h:

>https://github.com/mborgerson/xemu/blob/176b574403e0f4a08bfb1f8ab58e0f819a45cf81/hw/xbox/nv2a/shaders.c#L296-L312


>So, maybe I'm wrong.
It needs further investigation.
This might not be a bug in XQEMU, but a bug in the nxdk shader compilers?

From [JayFoxRox](https://github.com/JayFoxRox)

**Comment by abaire** [comment]
The defines match the fixed function piipeline. The programmable pipeline can use any input register in any way it chooses (and many games do use non-"standard" conventions, often just choosing to use sequential registers).

Personally I don't think this bug is important for xemu and it's not clear to me that it's actually caused any confusion in this project.

Generally bugs should not be brought over from xqemu without discussion w/ @mborgerson first to make sure they're actually applicable (apologies if you did discuss it and he thinks this is more important for xemu than I do).

**Comment by Triticum0** [comment]
No, I have not, matt can decide if he wants the issue reopen
