### ISSUE TITLE
Some Games have FMV's Flickers

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1049]
### Bug Description

Some games have FMVs that flicker
### Example:
https://user-images.githubusercontent.com/71127352/172928344-68ba9cff-0e1b-47d3-8a70-b0ffcac35dec.mp4

Games Affected:
https://xemu.app/titles/5451001d/#Broken-Sword-The-Sleeping-Dragon
https://xemu.app/titles/42560002/#Disney-s-Chicken-Little
https://xemu.app/titles/4947007a/#Dragon-Ball-Z-Sagas
https://xemu.app/titles/544d000d/#Disney-s-The-Haunted-Mansion
https://xemu.app/titles/55530060/#Far-Cry-Instincts-Evolution
https://xemu.app/titles/545100f4/#Nickelodeon-Tak-The-Great-Juju-Challenge

### Expected Behavior

Should not flicker

### xemu Version

Version: 0.7.29
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/69dcbe9b3081ee51d1468b1b7777b8b930bfba6c
Date: Wed Jun 8 05:09:16 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

**Comment by eternights** [comment]
[Final Fight: Streetwise](https://xemu.app/titles/43430013/#Final-Fight-Streetwise) too.

**Comment by abaire** [comment]
Hey @Triticum0 can you test whether PR #1146 also fixes these games when you have a chance?

**Comment by abaire** [comment]
Looking at Dragon Ball Z Sagas, I see that the FMV is rendered entirely via PVIDEO with no pgraph activity (so similar to but distinct from #1165).

In renderdoc, I see that pvideo_tex looks reasonable, and that the primary framebuffer texture is stale data (in my test case, it's the boot logo screen). The issue is that `pvideo_enable` is set to false every few frames, so that stale screen is rendered instead of the video content. When this happens, `d->pvideo.regs[NV_PVIDEO_BUFFER]` in `pgraph_render_display_pvideo_overlay` is `0`.

If I set a breakpoint in `pgraph_render_display_pvideo_overlay` and step through, this never happens, so at the moment I suspect there may be a timing issue where `NV_PVIDEO_BUFFER` is briefly cleared and the xemu UI thread just happens to fetch a frame during that interval.

UPDATE: Confirmed, if I set breakpoints in `pvideo_write`, the game is alternately setting `NV_PVIDEO_BUFFER` and `NV_PVIDEO_STOP` (probably between frames) and when xemu happens to fetch the display buffer during the small interval between it flashes up a frame without the video overlay.

**Comment by abaire** [comment]
I wrote a [test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/pvideo_tests.cpp) and was able to confirm that xemu's handling of the `NV_PVIDEO_STOP` is incorrect. Writing to the register only tears down the overlay if the 0th bit is 1. On hardware, setting `NV_PVIDEO_STOP = 0` keeps the PVIDEO content displayed, whereas on xemu, any write to the stop register hides the overlay.

**Comment by abaire** [comment]
@Triticum0 can you test #1168 to see if it fixes all of these games when you have a chance? I've confirmed it with Dragon Ball Z Sagas.

**Comment by Triticum0** [comment]
I tested it with  Dragon Ball Z Sagas and it did do anything

It only affects the In-game FMV so you won't see any flicker on the Intro FMV even on masters properly should have made a note in the pr,

https://user-images.githubusercontent.com/71127352/177773140-daaebb2a-0d91-4b8f-b10b-56387148cee9.mp4

**Comment by abaire** [comment]
> I tested it with Dragon Ball Z Sagas and it did do anything
> 
> It only affects the In-game FMV so you won't see any flicker on the Intro FMV even on masters properly should have made a note in the pr,

On my machine it definitely affects the attract mode FMV (let it sit on the "Press start" screen and it starts playing a movie after a minute or so). This game and that video is what I used to debug the issue and to verify the patch.
I also verified that on master, the intro movie for Tak... flashes but with my PR it no longer does.

@Triticum0 Can you double check that you're using the correct PR artifact? Maybe take a screenshot that captures the titlebar so we can verify the commit hash?

https://user-images.githubusercontent.com/448413/177799947-bc35e544-6da7-44d2-a433-4934a26baca6.mp4


https://user-images.githubusercontent.com/448413/177799982-2f284269-9e48-41cc-a76b-5f13d66bbc31.mp4

**Comment by Triticum0** [comment]
@abaire Yeah sorry, must of tested the wrong build. It fixed most of the games except for [Broken-Sword-The-Sleeping-Dragon](https://xemu.app/titles/5451001d/#Broken-Sword-The-Sleeping-Dragon) and [Disney-s-The-Haunted-Mansion](https://xemu.app/titles/544d000d/#Disney-s-The-Haunted-Mansion)

**Comment by Triticum0** [comment]
I will make another Issue for those games as there is a separate issue and you can close this issue once the pr has been merged

**Comment by abaire** [comment]
> I will make another Issue for those games as there a seperate issue and you can close this issue once the pr been merged

Sounds good, thanks for double checking!
