### ISSUE TITLE
Slow FMVs and menus in many games

### ISSUE THREAD

**Issue by rashvash** [xemu-project/xemu#1232]
### Bug Description

FMV's are slow and low FPS in many games. Games tested by me: Headhunter, Burnout 3, Tenchu, Ninja gaiden black, Indiana Jones. Games reported by others: Half-life 2,  Dreamworks games,  Black, Oddworld,  Burnout revenge
![2022-06-26_140909](https://user-images.githubusercontent.com/28275367/184479904-5a2240e1-2cc5-4b29-9f4d-3c11cfe34641.jpg)
![176174070-02c440fa-4c2c-44a3-ac5e-d6e6c7ca50d2](https://user-images.githubusercontent.com/28275367/184479906-6de910ed-59d0-4f52-821d-22fcefceb1c0.jpg)

Also low FPS in menus of many games (e,g, Indiana Jones and the Emperor's Tomb, Burnout 3)

### Expected Behavior

FMVs  and menus work normally and full-speed, with normal frame-rate.

### xemu Version

0.7.67, master.

### System Information

Win 7 x64, Ryzen 5 1600 AF, HD 7870, adrenalin-2020-21.5.2

**Comment by BParks21** [comment]
Having the same problem. Tested Conkers. Seems to get instantly worse when you move the emulator window around or go fullscreen.

**Comment by santiagogustavo** [comment]
+1 for me, i7-8665U CPU. Got the same results on Windows and Linux (deb) builds, with different machines.
Some games I tried do work well with FMVs: Blinx, Gunvalkyrie, JSRF.
Some others work with steady 60fps during gameplay, but the FMVs are painfully slow: Magatama, Conker, Kabuki Warriors (judge me)

**Comment by ehw** [comment]
Harry Potter and the Chamber of Secrets is another game with flow FMV, particularly in the FMV past the title screen.

**Comment by rashvash** [comment]
Congrats! Another issue solved

**Comment by rashvash** [comment]
Congrats! Another issue solved Rationale behind closure:  fanboish schoolkids dracc and his girlfriends being too hysterical.

**Comment by BParks21** [comment]
The fmv's still stutter in Conker's intro.

**Comment by draccfacc** [comment]
> The fmv's still stutter in Conker's intro.

Actually all of them stutter. From what I know rashvash closed all his xemu issues on github (though all the bugs discribed there) cause "Xemu moderators and developers being buncha stupid trolls and idiots who disrespect their testers and users" and they don't want to help such people in any way any more and rashvash won't take any part in xemu project in any way any more. So you'd better create you own issues (or re-create theirs). Personally I think rashvash did a good job by pointing FMVs and menus stutter problem out. But narcissist moderators and developers as usually spoilt it all. By fighting their free-willing testers and users Instead of fixing bugs. I confirm that Slow FMVs and menus in many games bug  still remain.

**Comment by dracc** [comment]
@draccfacc Are you telling me that you're not a rashvash alt?
