### ISSUE TITLE
Meta Graphical corruption After AMD 22.7.1

### ISSUE THREAD

**Issue by RinMaru** [xemu-project/xemu#1265]
### Bug Description

after AMD 22.7.1 the graphics in games will break at certain frames 

Destroy All Humans
![xemu-2022-09-21-21-13-51](https://user-images.githubusercontent.com/15071652/191637287-fb7638c0-2636-491a-83d7-935cd2d0aaf5.png)

Sonic Heroes
![xemu-2022-09-21-21-22-40](https://user-images.githubusercontent.com/15071652/191637843-cda02a51-daab-4e99-b49d-76cbfe6a8a99.png)

Grabbed By the Goulies
![xemu-2022-09-21-21-26-33](https://user-images.githubusercontent.com/15071652/191638221-83ddfd3e-7ee7-4708-9c48-e58b00ebab5c.png)

Dr Muto
![xemu-2022-09-21-21-35-40](https://user-images.githubusercontent.com/15071652/191639176-5b35f0a0-6300-474d-bdf1-6e36e7b86467.png)

### Expected Behavior

Graphical Corruption shouldn't Happen

### xemu Version

v0.7.70

### System Information

Windows 11
RX 6700XT 12GB
Ryzen 5 5600X
20GB DDR4

**Comment by Diegolol8000** [comment]
I also have the same problem with Grabbed By the Goulies and before I didn't have that error.
![xemu-2022-10-01-00-17-52](https://user-images.githubusercontent.com/114799340/193397949-66f851e5-a41d-48f3-9df8-b75e46f1b783.png)
![xemu-2022-10-01-00-18-28](https://user-images.githubusercontent.com/114799340/193397951-1bdd7ddd-388a-4568-adb9-4c1d3d84753c.png)

**system information**
Windows 10
AMD Ryzen 3 PRO 4350G with Radeon Graphics
AMD Radeon(TM) Graphics
16 GB

**Comment by RinMaru** [comment]
> **system information** Windows 10 AMD Ryzen 3 PRO 4350G with Radeon Graphics AMD Radeon(TM) Graphics 16 GB

What Architecture is the AMD GPU? Vega?

**Comment by Diegolol8000** [comment]
As far as I know, I don't think it's vegan, but in order to answer your question, I have more detailed information here:

**General Specifications**
Platform: Desktop
Product Family: AMD Ryzen™ PRO Processors
Product Line: AMD Ryzen™ 3 PRO 4000 Series Desktop Processors
# of CPU cores: 4
# of threads: 8
Max Boost Clock: Up to 4.0GHz
Base Clock: 3.8GHz
Total L1 cache: 256KB
Total L2 cache: 2MB
Total L3 cache: 4MB
TDP/Default TDP: 65W
AMD Configurable TDP (cTDP): 45-65W
Processor Technology for CPU Cores: TSMC 7nm FinFET
Unlocked: No
Package: AM4
Thermal Solution (MPK)
Wraith Stealth
Maximum temperature: 95°C
Release Date: 7/21/2020

**connectivity**
PCI Express version: PCIe® 3.0
Memory type: DDR4
Memory channels: 2
Maximum memory speed: Up to 3200MHz

**Graphics Capabilities**
Graphics Model: Radeon™ Graphics
# of GPU cores: 6
Graphics frequency: 1700 MHz

**Product ID's**
Tray OPN: 100-000000148
Product ID MPK:100-100000148MPK

**Comment by Diegolol8000** [comment]
As far as I know, I don't think it's Vega, but in order to answer your question, I have more detailed information here:

General Specifications
Platform: Desktop
Product Family: AMD Ryzen™ PRO Processors
Product Line: AMD Ryzen™ 3 PRO 4000 Series Desktop Processors
Number of CPU cores: 4
Number of threads: 8
Max Boost Clock: Up to 4.0GHz
Base Clock: 3.8GHz
Total L1 cache: 256KB
Total L2 cache: 2MB
Total L3 cache: 4MB
TDP/Default TDP: 65W
AMD Configurable TDP (cTDP): 45-65W
Processor Technology for CPU Cores: TSMC 7nm FinFET
Unlocked: No
Package: AM4
Thermal Solution (MPK)
Wraith Stealth
Maximum temperature: 95°C
Release Date: 7/21/2020

connectivity
PCI Express version: PCIe® 3.0
Memory type: DDR4
Memory channels: 2
Maximum memory speed: Up to 3200MHz

Graphics Capabilities
Graphics Model: Radeon™ Graphics
Number of GPU cores: 6
Graphics frequency: 1700 MHz

Product ID's
Tray OPN: 100-000000148
Product ID MPK:100-100000148MPK

**Comment by RinMaru** [comment]
this is fixed as of 22.11.1 but performance has GREATLY suffered
