### ISSUE TITLE
"Unsupported machine type" XQEMU gives this error when I try to run it. (Detailed: xbox,accel=kvm:hax:whpx,kernel_irqchip=off,bootrom=/home/barant/Desktop/xboxemu/xBios/mcpx_1.0.bin,short_animation: unsupported machine type)

### ISSUE THREAD

**Issue by barantamur** [xemu-project/xemu#14]
When I try to run the program, it gives the error shown. (xbox,accel=kvm:hax:whpx,kernel_irqchip=off,bootrom=/home/barant/Desktop/xboxemu/xBios/mcpx_1.0.bin,short_animation: unsupported machine type)
this is what qemu-gui runs: 

/usr/bin/qemu-system-x86_64 -cpu pentium3 -machine xbox,accel=kvm:hax:whpx,kernel_irqchip=off,bootrom=/home/barant/Desktop/xboxemu/xBios/mcpx_1.0.bin,short_animation -m 128M -bios /home/barant/Desktop/xboxemu/xBios/xbox-5838.bin -drive file=/home/barant/Desktop/xboxemu/xbox_hdd.qcow2,index=0,media=disk -drive "index=1,media=cdrom,file=/home/barant/Downloads/HaloCombatEvolved_USA_v109_redump_27162/Halo - Combat Evolved (USA) (v1.09).iso" -qmp tcp:localhost:4444,server,nowait -display sdl -device usb-hub,port=3 -device usb-xbox-gamepad-sdl,index=0,port=3.1 -gdb tcp::1234

Any ideas how to solve that problem?

**Comment by mborgerson** [comment]
A few things:
* It looks like you're launching stock QEMU, which doesn't have the Xbox machine.
* If you intend to build from source, please use the build.sh script as described on the wiki, then you can launch using "./i386-softmmu/qemu-system-i386" (for now).
* I'm not sure where you've derived these command line arguments, but I'm guessing you've used xqemu-manager; xemu doesn't require such arguments to be provided so you can just launch the app and configure your settings using the UI.

If you're using Ubuntu, I recommend using my PPA (provided on the wiki) instead of building from source.
