### ISSUE TITLE
Booting Real Disk Drive

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1476]
### Feature Request

Feature request for `xemu` to be able to booting real physical disk drive. 
It's probably already capable to, but not user configurable as `xemu` build `qemu` boot flags internally.

### Additional Context

I want to use `xemu` for disk related tasks such as (re)building disk, ripping games, etc. This probably will be an alternative to XBHDM, file transfer tools, etc.

**Comment by BiatuAutMiahn** [comment]
why not use hexen to setup the tools on the hdd? the bios boots c:\default.xbe

**Comment by GoTeamScotch** [comment]
Xemu does indeed already support this (kind of). Taking advantage of Qemu's built-in ability to mount host drives, we can pass Xemu a physical host drive instead of a drive image. I tested using an IDE-to-USB adapter and it worked, with some caveats.


**Procedure:**
- Open Xemu's toml file. On Windows, this is located here: `%AppData%\xemu\xemu\xemu.toml`
- In the toml file, remove the line that specifies where your Xbox HDD image is located. Save the file. This is needed or else Xemu will complain about there already being a HDD present later.
- Open command prompt as an administrator. Run the following command to find the disk number that your physical Xbox HDD is represented as in Windows as: `wmic diskdrive list brief`. After running this command, you'll see a list of disks attached to your PC. Find your Xbox's disk in the list and note its number, for example "\\.\PHYSICALDRIVE2".
- Launch Xemu, passing it your physical Xbox's HDD number in the following format: 
`xemu -drive file=\\.\PHYSICALDRIVE2,format=raw`

Your real Xbox's HDD will now be attached and usable from within Xemu.

Notes:
- I could not get Xemu to boot into my dashboard of choice on my HDD. I had to use Quix to create an XISO of an app (UnleashX) and set that as my DVD disc image in Xemu. It then loaded UnleashX and I could use the file browser to browse my Xbox HDD's contents (edits/writes seemed to work).
- Be careful to choose the correct host disk. During testing, I accidentally chose my main OS disk (numbers changed after reboot) and it caused my PC to freeze and reboot. It might be possible to corrupt your other non-Xbox hard disks. Use with caution.
- Tested using an IDE-to-USB adapter using an unlocked WD 8GB (stock) hard drive. When I tried using my 4TB Xbox HDD (native SATA), Cromwell reported it as 1.8TB, likely due to some LBA issue (?).
- I can't seem to get XBE's to launch from my Xbox HDD. Would love others to test to see if more progress can be made. After booting into my UnleashX XISO, I tried launching the same XBE from my Xbox's HDD and Xemu soft-locked.

P.s. this doesn't seem like a good method to build HDD's. Just use FATXplorer.

Screenshot showing UnleashX's file explorer, browsing my (real) Xbox HDD:
![image](https://github.com/xemu-project/xemu/assets/11036843/c68eb447-883f-4881-a4a6-329941044579)

**Comment by rizaumami** [comment]
This issue was made before I realized that on Linux system we only need to run `xemu` as superuser/root.
With root, we can access the real disk in `/dev/` and do everythings with it as we use the real Xbox; e.g. use installer to rebuild disk.

The only known problem is with Audio. `xemu` throw some complaints on missing soundcard (or else, it's escaped my mind right now). Not a big problem as using root to run `xemu` is not intended behaviour.
