### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [xemu-project/xemu#1498]
### Feature Request

I would like for you to port xemu to iOS so I can have all 4 popular 6th gen console emulators on my phone:

**Comment by Spidy123222** [comment]
> ### Feature Request
> 
> I would like for you to port xemu to iOS so I can have all 4 popular 6th gen console emulators on my phone:
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

It's possible as there's a android attempt using termux from someone in server that's not the dev using zink. From what I gather a android port would be better first then ios as iOS has more restrictions. Since qemu exists on iOS without much problem, using tcg without jailbreak, it would take some referencing I would assume and some pojavlauncher references to use zink on ios. Expect for it to take a while to do a port if anything happens. Also I would rename this to "iOS Support" as there's other sideloading programs that can run jit based apps like sidestore (I personally work on with others), sideloady and ofc Xcode.

**Comment by MikeyMK** [comment]
> > ### Feature Request
> > I would like for you to port xemu to iOS so I can have all 4 popular 6th gen console emulators on my phone:
> > ### Alternatives
> > _No response_
> > ### Additional Context
> > _No response_
> 
> It's possible as there's a android attempt using termux from someone in server that's not the dev using zink. From what I gather a android port would be better first then ios as iOS has more restrictions. Since qemu exists on iOS without much problem, using tcg without jailbreak, it would take some referencing I would assume and some pojavlauncher references to use zink on ios. Expect for it to take a while to do a port if anything happens. Also I would rename this to "iOS Support" as there's other sideloading programs that can run jit based apps like sidestore (I personally work on with others), sideloady and ofc Xcode.

Would you be able to provide some more info on the android attempt? Thank you!

**Comment by mborgerson** [comment]
If someone wants to get xemu running on iOS and support it, that would be great. That said, I don't think we need an open issue for the request, and honestly I don't plan to do this any time soon.
