### ISSUE TITLE
Phantom Crash: Poor gameplay performance

### ISSUE THREAD

**Issue by BigCIAman** [xemu-project/xemu#1546]
### Title

https://xemu.app/titles/47450002/#Phantom-Crash
GE-002 [47450002]

### Bug Description

The game has very low framerate when you enter an arena, specially in Shibuya, i can only manage to get 15-10 fps, the game seems to run fine only when there's only 1 opponent on the arena, maybe a problem of having  to many entities moving around the map

### Expected Behavior

The game should be able to run at a constant 30 fps, the game runs way faster on original hardware as seen on this video
https://www.youtube.com/watch?v=kxrn6RMjVIA

### xemu Version

Version:      0.7.116
Branch:       master
Commit:       b3fc80b3a83fa99aeb541a0c665cfb596cedd71c
Date:         Sun Oct 22 07:25:29 UTC 2023

### System Information

CPU:          Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
OS Platform:  Windows 10
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 545.84
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

last compatibility report set the game's compatibility to perfect, which is not the case, i'd set it to start or playable if you can call playing the game at 10 fps "playable"

**Comment by wxvu** [comment]
I did the latest compatibility report for this game. I marked it as "Perfect" since I was unsure if performance factored into compatibility reports, as by all other metrics the game is perfectly emulated. 

If performance does factor into it, I would question even marking it as playable. The game has unplayable performance on most people's rigs compared to other titles, including mine (i5-7600k) and I very much doubt even top-of-the-line hardware gets performance that is comparable to real hardware. This issue report might have some merit behind it.

**Comment by mborgerson** [comment]
Performance is a factor in reports--generally if some machine can play the game then it is considered playable.

This video looks very playable <https://www.youtube.com/watch?v=t_5GPmKMFKY>. Presumably this is your video @forrvalhalla, as like you the video poster claims to have an i5-7600k? Maybe there is some other level that has much worse performance that should be tested?

**Comment by wxvu** [comment]
Yes, that is my video. The upload date on it is wrong though, it was unlisted for a long time, I recorded it the day it became playable haha.

That video..... if I'm honest, is a bit misleading. Performance is usually never that good, especially on other maps. As soon as you get into direct combat and/or let more enemies load into the field the performance gets much worse. In addition, the game needs DSP Processing which makes the performance even worse (This is mentioned in the compat report.)

Just for the sake of it I went and downloaded a fresh version of Xemu and hopped into all three maps and got screengrabs of the FPS, if it's relevant.
![Screenshot 2023-10-27 18-04-40 - Copy](https://github.com/xemu-project/xemu/assets/53349573/6fef723c-dc4d-4d1f-b62e-641feb93534d)

**Comment by izanuggie** [comment]
I'm using xemu version 0.7.121, and the only time the frames dropped to 15 where RIGHT as you load in to the arena and then they jumped back up to 27, otherwise throughout the game I held a 25-30 range, even under heavy fire.
It could be you need to tamper with your emulation settings or change parts in your computer, but the game played perfectly fine for me in all menus and arenas. 

However, I am running it on these specs:

CPU: AMD Ryzen 9 5900X 12-Core @ 3.70 GHz
OS: Windows 11
OS Version: 22621.3627
GPU Model: NVIDIA GeForce RTX 3070 Ti
Graphics Driver Version: 31.0.15.5222

![Phantom Crash2](https://github.com/xemu-project/xemu/assets/169428437/ffd4002a-2f43-4103-a651-71bd668256cc)

![Phantom Crash1](https://github.com/xemu-project/xemu/assets/169428437/0328b766-6658-471a-b073-45706e928fc7)

**Comment by mborgerson** [comment]
We'll consider the issue resolved for now then if performance is acceptable on this machine. Overall performance of xemu will continue to improve.
