### ISSUE TITLE
Just a Quick Question

### ISSUE THREAD

**Issue by WindowsNinetyTen** [xemu-project/xemu#1575]
Would an Intel-based computer be at an advantage for this program because of the Xbox being Intel-based?
Also, for the Xbox is Windows and DirectX and x86-based, would it be possible to make a version that can virtualize the functions present in regular Windows and DirectX and emulate only the special functions that are absent in regular Windows and DirectX?

**Comment by Spidy123222** [comment]
Having intel chip wouldn't really have an advantage nowadays. Chips nowadays are pretty different and behavior would be different. I say no because xemu uses jit(qemu tcg pipeline) and the only reason you would see a performance uplift in x86 is because of lack of hardfpu on arm devices currently. But mostly it sounds like your looking for cxbx-reloaded which is only for windows that acts like a translation layer for the most part.

**Comment by WindowsNinetyTen** [comment]
I understand. I've heard of CXBX-Reloaded, by the way. I was asking due to similarities in architecture, despite the differences. Also, my desktop has an Intel Core i5.

**Comment by BiatuAutMiahn** [comment]
> Would an Intel-based computer be at an advantage for this program because of the Xbox being Intel-based? Also, for the Xbox is Windows and DirectX and x86-based, would it be possible to make a version that can virtualize the functions present in regular Windows and DirectX and emulate only the special functions that are absent in regular Windows and DirectX?

that's basically what [cxbx](https://cxbx-reloaded.co.uk/) is.

**Comment by Spidy123222** [comment]
> I understand. I've heard of CXBX-Reloaded, by the way. I was asking due to similarities in architecture, despite the differences. Also, my desktop has an Intel Core i5.

I mean it's likely possible to make a NCE (native code execution) type code like yuzu does but not sure how accurate it would be doing that then. The concern is micro-architecture difference causing inaccurate results.

**Comment by BiatuAutMiahn** [comment]
For a high-level/crude explanation, x86 vs ARM is like performing `4*4=16` on x86 with a multiplier instruction, but with ARM you have to do `4+4+4+4=16`. (Disclaimer: realistically arm supports multiplication) Same operation more clock cycles. Certain instructions are simpler and thus require more work to achieve the same result.  ARM is faster than x86 as a result of the simpler instructions. Nowadays though ARM actually competes with x86. Like @Spidy123222 says ARM falls short with floating point arithmetic which is essential if you intend to execute code that expects those floating point instructions. As a result the system needs to emulate those instructions at the cost more cycles than with an x86 CPU.

**Comment by BiatuAutMiahn** [comment]
> CXBX-Reloaded

When I first experienced CXBX I was really interested in the whole API wrapper concept. It makes sense as the Xbox did run a stripped down version of win2k, xbe's are based on exe files...it doesn't take much to modify them to be able to execute on PCs. Before CXBX-Reloaded, CXBX would convert the xbe to an exe and then attempt to patch the exe's API calls to the windows' equivalent. If I'm not mistaken the main problem is handling the nv2a GPU and timing with the function calls.

**Comment by WindowsNinetyTen** [comment]
And I hear that CXBX-Reloaded also does API wrapping like this? By the way, a similar program for Xbox One games is being developed, called XboxONEmu. The Xbox 360, on the other hand, is the odd one out, using a PowerPC architecture instead of x86-x64.

**Comment by BiatuAutMiahn** [comment]
The last I knew CXBX-Reloaded loads the xbe into memory patches it so that it's executable on modern windows, then runs the game while hooking into the APIs dynamically. The last time I watched the project they were implementing some LLE to handle some of the GPU/APU calls because HLE couldn't really keep up. It's complicated, some games worked fine using HLE, but ultimately LLE albeit slow yielded better results. It's still being developed [https://github.com/Cxbx-Reloaded/Cxbx-Reloaded](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded) though I haven't followed since Xemu as it had a more effective approach.

**Comment by BiatuAutMiahn** [comment]
Personally, I loved the idea of a tool that simply recompiles the xbe to be executable on windows. 

Edit: [https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Cxbx-Reloaded-overview](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Cxbx-Reloaded-overview) Yes, they're doing exactly what you were talking about in the OP.

**Comment by WindowsNinetyTen** [comment]
Okay then. I also like the concept of such a tool. CXBX-Reloaded is therefore my first choice for playing Xbox on Windows.

**Comment by dracc** [comment]
May I please remind you folks that this isn't a forum for general
discussion? You're sending emails to upwards of 2200 inboxes with every
comment right now.

If you just want to chit-chat, please consider joining the project's
[Discord server](https://discord.gg/ayyjsuM).
