### ISSUE TITLE
Disc compression support 

### ISSUE THREAD

**Issue by strich** [xemu-project/xemu#1584]
### Feature Request

There have been a few issues raised over the years about providing any kind of compassion in to of the images be it CHD or some other format, and it seemed some consensus was being found but seemingly no further progress and all previous issues locked for comment. 
https://github.com/xemu-project/xemu/issues/238
https://github.com/xemu-project/xemu/issues/129

Is there a plan to progress this?

**Comment by mborgerson** [comment]
Afaik nobody is working on this feature. There are a number of higher priority tasks. Issue was locked because the conversation was not very productive, and as I mentioned in the comments general chat about the topic is welcome on Discord instead. If you are very motivated and want to work on the feature and suggest a patch, you are welcome to. If you want to chat about it with others, join Discord.

**Comment by strich** [comment]
Wait why are you pushing discussions off GitHub? You need to be keeping these issues open so others can understand the status of features and potentially contribute. The previous issue you closed was actually reaching consensus and was productive but now no one can help move it along and the whole conversation has to start again in an issue like this.
This is very weird behavior for a repo on GitHub.

Ime5 of the main things that needs determining is whether the maintainers will even accept a CHD solution. Will they?

**Comment by brad86m** [comment]
A simple "We're not implementing the request" would be far better than "maybe, maybe not" each time someone asks. It's a much wanted feature, and not being able to discuss it is not a great look.

**Comment by abbotadmin** [comment]
> A simple "We're not implementing the request" would be far better than "maybe, maybe not" each time someone asks. It's a much wanted feature, and not being able to discuss it is not a great look.

It's quite clear the maintainer has some bias against CHD support that they don't care to defend as they've done everything they can to close or lock any threads about it. Anyone who would consider wanting to contribute this should probably look at another project to support sadly. :/

**Comment by iamdark24** [comment]
> A simple "We're not implementing the request" would be far better than "maybe, maybe not" each time someone asks. It's a much wanted feature, and not being able to discuss it is not a great look.

No and maybe are different though. No means it not ever going to be on the radar while maybe means it carries a chance that it could make it to a roadmap. Just because something is a popular request doesn’t mean it’s on the roadmap as there are currently larger issues to investigate. I would love to see progress on audio issues before something like this, but that’s just me.
