### ISSUE TITLE
Xemu in M1 Ipad Pro

### ISSUE THREAD

**Issue by eduo** [xemu-project/xemu#1635]
### Feature Request

Are there plans for an Apple Silicon release for mobile devices? (essentially for M1 iPad Pro or Apple Vision) seeing as the version for Apple Silicon Macs is now universal?

### Additional Context

I'm surprised I couldn't see this in the past issues, so even if the answer is negative I thought I'd ask just so there's a record for people looking for it in the future.

**Comment by Spidy123222** [comment]
> ### Feature Request
> 
> Are there plans for an Apple Silicon release for mobile devices? (essentially for M1 iPad Pro or Apple Vision) seeing as the version for Apple Silicon Macs is now universal?
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> I'm surprised I couldn't see this in the past issues, so even if the answer is negative I thought I'd ask just so there's a record for people looking for it in the future.

So not really at the moment from what I see from discussion. There's a Vulkan backend being developed that would make it possible to even have an image. Just because it's made for apple silicon doesn't mean it's fully universal. There is still workarounds iOS/ipadOS developers need to do to get some programs working on the OS but it does help. 

It is possible to do however. There is already ports of qemu for example like utm. Biggest hurdle is performance and the workarounds. For performance aarch64 builds don't have hardfpu ability which makes it harder to run games atm, not like it's impossible as I use a m2 pro MacBook and it runs slightly better than the steam deck in Xemu even though single core performance is much greater. If one was to make a mobile app of Xemu. I would advice getting hardfpu on aarch64 builds first and ofc wait until Vulkan backend is released.

Yes you can sideload apps using developer tools currently in all regions not the eu stuff if some were wondering using tools like altstore or SideStore (I develop with others) to make it much easier for users to do. Can allow jit using a debugger which this can be used on non Mac systems, although being different atm at certain versions currently but is being worked on. 

This also applies to android systems btw. Since Xemu only has desktop OpenGL 4.0. There is no mobile compatible video backend to use. There is likely less workarounds needed on android systems here.

**Comment by mborgerson** [comment]
There are not plans to support it. If you want to work on it though you are welcome to, but I expect it's not really even worth doing unless Apple relaxes their policy on JIT code generation
