### ISSUE TITLE
Halo 2: Fog Issues

### ISSUE THREAD

**Issue by Ernegien** [xemu-project/xemu#1643]
### Title

https://xemu.app/titles/4d530064/#Halo-2

### Bug Description

Environmental fog in the Backwash multiplayer DLC map interferes significantly with player visibility making it unplayable; some kind of plane clipping issue? HUD elements and first person player models remain unaffected, environment decals and lighting are marginally unaffected.

Install DLC -> Main Menu -> Split Screen -> Game Setup -> Change Map -> Backwash

![xemu-2024-05-09-00-46-07](https://github.com/xemu-project/xemu/assets/382923/fcbbdb9a-178e-46eb-9df4-7a382978b367)

https://github.com/xemu-project/xemu/assets/382923/21f78a22-9645-4b1c-bd1e-3dffa6c2b115

### Expected Behavior

This is how it's rendered on real hardware

![10 231 50 176-image6](https://github.com/xemu-project/xemu/assets/382923/94f0f788-e96d-40a4-8114-855c37662467)
![10 231 50 176-image7](https://github.com/xemu-project/xemu/assets/382923/f5901853-61d3-42b8-b6d1-98e962e4323d)
![10 231 50 176-image8](https://github.com/xemu-project/xemu/assets/382923/2a7d666e-49ed-4f3b-9e76-f0fe3f08ed99)

### xemu Version

Version:      0.7.121
Branch:       master
Commit:       5a144a3fd3770fb730027dbab406ce71218bf966
Date:         Mon May  6 23:03:05 UTC 2024

### System Information

CPU:          AMD Ryzen 7 4800H with Radeon Graphics         
OS Platform:  Windows
OS Version:    23H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver:       4.0.0 NVIDIA 551.23
Shader:       4.00 NVIDIA via Cg compiler

**Comment by 0Alastair1** [comment]
possibly related to https://github.com/xemu-project/xemu/issues/1523

**Comment by Fox-GAMING** [comment]
@Ernegien Hello, sorry for this being off topic, but I've been trying to find a way to contact you regarding your Forza texture extraction tools and your general knowledge of the game, as I am trying to export the map for personal use. Your FTexExtract tool doesn't seem to be working, and I also have some questions, mainly about UVs, as I am wondering if there is a way to extract UVs from the game rather than manually (Tediously) redoing them.
