### ISSUE TITLE
Is there a Patreon where I can directly support the creators 

### ISSUE THREAD

**Issue by eltomas2003** [xemu-project/xemu#182]
Rpcs3 has a [patreon](https://www.patreon.com/Nekotekina) where I can support the creators, and can get the game I would like playable prioritized on the emulator. It could also motivate developers to work on the project full time. Does Xemu have something similar?

**Comment by Ernegien** [comment]
Matt's patreon can be found [here](https://www.patreon.com/mborgerson) where your support would be much appreciated, but I wouldn't expect preferential treatment as you might with others.

**Comment by mborgerson** [comment]
There is not an official project Patreon. 

However, if you like my work on the project and want to shoot me a couple bucks, I do have a [personal Patreon](https://www.patreon.com/mborgerson). Tips are appreciated but not required by any means. This is a passion project.

As for specific games, you are welcome to join the xemu Discord server and chat about your favorite game. We can take a look and possibly do what's necessary to unblock it.

Please be aware that there is no schedule and no guarantee of timeline. This is a hobby project that I, and others, work on for fun. Even with generous donations from people, it's not a viable replacement for full time employment, and that's okay because this is a passion project.

I hope you will come chat on the xemu Discord server for updates about your favorite games and other xemu news, and thanks again for your generosity!
