### ISSUE TITLE
allow loading default.xbe directly from extracted isos

### ISSUE THREAD

**Issue by eadmaster** [xemu-project/xemu#19]
i think this could help with the testing

**Comment by mborgerson** [comment]
Thanks, but this is not a planned feature.

**Comment by tastyratz** [comment]
I'd really love to see this myself. I'm not opening another new git issue on it, but, extracted folders are much easier to manage instead of repacking into iso's for no reason. I'd really love to see native XBE support (like CXBX-R has). I hate maintaining 2 different libraries.

Load folder as ISO feels like an easy feature.
