### ISSUE TITLE
Debug Kernels broken after MCPX overlay fix

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#243]
Appears #100 broke using real debug kernels.

**Comment by Ernegien** [comment]
I'll have to dump mine to confirm but I speculate we'll need to leave the upper portion of address space writeable in the case an MCPX ROM isn't specified (since normally debug/devkit MCPX X2's wouldn't have that special bootrom mapped). You can test this theory by copying the upper 512 bytes of your debug BIOS ROM into a separate file and using that as the MCPX ROM instead; I would assume it then functions as intended.

**Comment by GXTX** [comment]
Seem to be a workaround, confirmed.

**Comment by Ernegien** [comment]
This appears to affect Cromwell images as well (in a different way most likely) which I'll also investigate and fix.

**Comment by Ernegien** [comment]
The current Cromwell workaround I'm suggesting is to start by patching [here](https://github.com/XboxDev/cromwell/blob/b5e315ee28dfa41c0a3557f6f8ee8afdcb7ca58e/boot_rom/Xcodes.h#L290) with the following:

```
// overflow trick (orig)
// jmp    0x8:0xFFFC1000
//xcode_poke(0x00000000, 0xfc1000ea);
//xcode_poke(0x00000004, 0x000008ff);

// overflow trick (newer xemu-friendly method)
// mov eax, 0xFFFC1000
// jmp eax
// nop
xcode_poke(0x00000000, 0xFC1000B8);
xcode_poke(0x00000004, 0x90E0FFFF);
```

Otherwise, xemu doesn't like the far jump immediately after the MCPX overlay has been disabled and rollover to address 0 happens; instead it ends up resetting with the following if running xemu with `-d int -no-reboot -no-shutdown` and lpc debug strings enabled.

```
xbox_lpc_reset
xbox_lpc_config_write: 84 8001 4
xbox_lpc_config_write: 10 8001 4
xbox_lpc_config_write: 4 3 4
xbox_lpc_config_write: 60 400 4
xbox_lpc_config_write: 4c fdde 4
xbox_lpc_config_write: 9c 871cc707 4
xbox_lpc_config_write: b4 f00 4
DEACTIVATING BOOT ROM
xbox_lpc_config_write: 80 2 1
check_exception old: 0xffffffff new 0xd
     0: v=0d e=0000 i=0 cpl=0 IP=0008:00000000 pc=00000000 SP=0010:00000000 env->regs[R_EAX]=80000802
EAX=80000802 EBX=000000d1 ECX=00000000 EDX=00000cfc
ESI=0008f000 EDI=00006000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 00000000 ffffffff 00cf9b00 DPL=0 CS32 [-RA]
SS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
DS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 00000000 0000ffff 00009300 DPL=0 DS16 [-WA]
GS =0000 00000000 0000ffff 00009300 DPL=0 DS16 [-WA]
LDT=0000 00000000 0000ffff 00008200 DPL=0 LDT
TR =0000 00000000 0000ffff 00008b00 DPL=0 TSS32-busy
GDT=     ffffffd8 00000018
IDT=     ffffffd8 00000018
CR0=00000011 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
CCS=00000004 CCD=00000cfc CCO=ADDB    
EFER=0000000000000000
check_exception old: 0xd new 0xd
     1: v=08 e=0000 i=0 cpl=0 IP=0008:00000000 pc=00000000 SP=0010:00000000 env->regs[R_EAX]=80000802
EAX=80000802 EBX=000000d1 ECX=00000000 EDX=00000cfc
ESI=0008f000 EDI=00006000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 00000000 ffffffff 00cf9b00 DPL=0 CS32 [-RA]
SS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
DS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 00000000 0000ffff 00009300 DPL=0 DS16 [-WA]
GS =0000 00000000 0000ffff 00009300 DPL=0 DS16 [-WA]
LDT=0000 00000000 0000ffff 00008200 DPL=0 LDT
TR =0000 00000000 0000ffff 00008b00 DPL=0 TSS32-busy
GDT=     ffffffd8 00000018
IDT=     ffffffd8 00000018
CR0=00000011 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
CCS=00000004 CCD=00000cfc CCO=ADDB    
EFER=0000000000000000
check_exception old: 0x8 new 0xd
```

Upon further inspection it looks like the Cromwell image clobbers the first part of the GDT/IDT table(s) at MCPX ROM offset 0x1D8 so it's looking like xemu's lack of cache emulation is at fault here, doh! After restoring the table to its original form in the Cromwell image things act as intended.

Orig
![image](https://user-images.githubusercontent.com/382923/111583252-1c010e80-878a-11eb-8bf5-21aabe854302.png)

Fixed
![image](https://user-images.githubusercontent.com/382923/111583455-75693d80-878a-11eb-8804-ab5008807b1e.png)

One potential workaround (albeit extremely hacky) within xemu to allow legacy Cromwell images to boot with current MCPX disablement logic is to modify it slightly as follows, but we'd have to further test this against anything out there to determine what else might do things differently as they'd all have to issue the magic transaction otherwise resets likely won't work properly.

```
static void xbox_lpc_reset(DeviceState *dev)
{
    PCIDevice *d = PCI_DEVICE(dev);
    XBOX_LPCState *s = XBOX_LPC_DEVICE(d);
 
    if (s->is_safe_to_enable_mcpx_rom)
    {
        xbox_lpc_enable_mcpx_rom(PCI_DEVICE(dev), true);
        s->is_safe_to_enable_mcpx_rom = false;
    }
}
 
static void xbox_lpc_config_write(PCIDevice *dev,
                                    uint32_t addr, uint32_t val, int len)
{
    XBOXPCI_DPRINTF("%s: %x %x %d\n", __func__, addr, val, len);
 
    XBOX_LPCState *s = XBOX_LPC_DEVICE(dev);
    if ((addr == 0x6C) && (val == 0xe065491))   // magic!
    {
        s->is_safe_to_enable_mcpx_rom = true;
    }
 
    if (((addr == 0x80) && (val & 2))) {
        xbox_lpc_enable_mcpx_rom(dev, false);
    }
    
    pci_default_write_config(dev, addr, val, len);
}
```

Since this is pretty much a Cromwell-based issue (it may not even be that widespread, and only present on newer debug/versioned builds) only however, perhaps a legacy boot mode setting in the ini is cleaner and more favorable however. Whether or not that gets exposed via the UI is up for further debate. Thoughts?

**Comment by Ernegien** [comment]
I can't seem to reproduce the debug bios boot failures in master for 5849, 5788, 5659, or 5455 taken from the recovery discs. However, 4039 and earlier (not comprehensive, just spot-checked what I have and assume it's the same for the rest) seem to have various issues; probably hardware version detection expectations etc. I still need to test those against earlier xemu builds to see when (if ever) they've worked. What's the version(s) and hash(es) of bios image(s) you're currently testing against, and what's the last working version of xemu?
