### ISSUE TITLE
Buffy the vampire Slayer: Background graphics are not rendered correctly 

### ISSUE THREAD

**Issue by m-mkhaimer** [xemu-project/xemu#292]
https://xemu.app/titles/45410012/#Buffy-the-Vampire-Slayer

### Bug Description
Background graphics are not rendered correctly, the background is moving in front of other objects which may cause problems in latter levels

Steps to reproduce this issue:
1. Play the first 2 minutes of the game, till you see that the backgrounds are moving, it makes the game unplayable in latter missions
https://youtu.be/6Q8U97FmFUY?t=77

![image](https://user-images.githubusercontent.com/84676682/119268531-b3079e00-bbf3-11eb-8244-d2607070a867.png)

https://youtu.be/6Q8U97FmFUY?t=310

![image](https://user-images.githubusercontent.com/84676682/119268575-de8a8880-bbf3-11eb-99af-702d879a922d.png)

### Expected Behavior

See videos below
https://youtu.be/flePzU8HukE?t=189
https://youtu.be/flePzU8HukE?t=407
![image](https://user-images.githubusercontent.com/84676682/119268683-5bb5fd80-bbf4-11eb-9a19-9f6cf0e1307d.png)

### Version

* Version: build-202105021910
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 64| 
| CPU			| I7 4790K| 
| Graphics Device	| NVIDIA 970| 
| Graphics Driver	| (...)			| Unkown

**Comment by felixlang** [comment]
This appears to be fixed in a recent update.

Windows 10 20H2
core i7 11700K
RTX 3080 FE
32 GB RAM

xemu v0.6.1-12-ga8c73197da


![20211005084146_1](https://user-images.githubusercontent.com/20476188/136035333-fb299df9-a727-42cf-9e37-86246e94cbcf.jpg)

![20211005084027_1](https://user-images.githubusercontent.com/20476188/136035370-b08ea4b6-820f-44a9-9afe-e56aee9ba867.jpg)

**Comment by mborgerson** [comment]
Thanks for the update @felixlang
