### ISSUE TITLE
Crash Twinsanity : Missing/Hidden Geometry

### ISSUE THREAD

**Issue by Foxlum** [xemu-project/xemu#299]
### Title Information

* Titles: VU-054 [56550036]
* https://xemu.app/titles/56550036/

### Bug Description

Steps to reproduce this issue:
1. Simply start the game and get to the title screen.

[Video](https://streamable.com/c1wj0n
)

### Expected Behavior

I should be able to see 3d geometry.
### Version

* Version: 0.5.2-18-g12b58544b1
* Last-known Working: f8a632645c6fea35efa7ad7acd01d22784dc8f8d

### System Information

DDR4 8 GB of RAM (2GB used for VRAM)

| Field | Value |
|-------|-------|
| OS			| Windows 21H1		| 
| CPU			| AMD Ryzen 5 3500U @	 2.10Ghz	| 
| Graphics Device	| AMD Integrated Vega 8		| 
| Graphics Driver	| Adrenalin 21.5.2 |

**Comment by Xcedf** [comment]
The whole black screen issue caused by texture cache rewrite, f4e73dd commit IIRC, before it game was extemely slow but rendered correctly
for some reason changing resolution scaling affects this
1xIR nothing changed
![48](https://user-images.githubusercontent.com/7060586/120286569-10bc7a00-c2c7-11eb-84f5-db6d029ec8e6.jpg)
2xIR
![49](https://user-images.githubusercontent.com/7060586/120286598-1ade7880-c2c7-11eb-997a-4e1251f6904d.jpg)
![50](https://user-images.githubusercontent.com/7060586/120286602-1c0fa580-c2c7-11eb-9794-8026564814fe.jpg)
