### ISSUE TITLE
pfifo.c:423 assertion

### ISSUE THREAD

**Issue by MasonT8198** [xemu-project/xemu#306]
### Title Information

* Titles: EM-009 [454d0009]
* https://xemu.app/titles/454d0009/#FlatOut

### Bug Description

Flatout has working fmvs, working menus, however when launching into a race you are greeted with the assertion
`xemu: ../hw/xbox/nv2a/pfifo.c:423: pfifo_run_pusher: Assertion false' failed.

Upon game ejection you are greeted with: `xemu: ../hw/xbox/nv2a/pgraph.c:4304: pgraph_render_display_pvideo_overlay: Assertion in_pitch >= in_width * 2 failed.`
`

Steps to reproduce this issue:
1. Launch a race in-game (For Flatout)
2.

### Expected Behavior
You should be able to get past this opening launch screen and begin a race

### Version

* Version: v0.5.2-21-gf72f9be767

### System Information

| Field | Value |
|-------|-------|
| OS			| (...)			| 
| CPU			| (...)			| 
| Graphics Device	| (...)			| 
| Graphics Driver	| (...)			|

**Comment by Triticum0** [comment]
Other titles affected:
https://xemu.app/titles/54510024/#WWE-WrestleMania-21

**Comment by Triticum0** [comment]
Other titles affected:
Midnight Club 3: DUB Edition [54540079]https://github.com/mborgerson/xemu/issues/349

**Comment by Triticum0** [comment]
This was fixed in #430 it should be closed

**Comment by Triticum0** [comment]
@mborgerson I retested all the games with this assertion, and they still crash. I Don't know if is NTSC of gpu vender specific, but WWE WrestleMania 21 and Flatout 1 and 2 still crashes with this assertion on my intel and amd configurations . I don't know how Alfman was able to make it ingame. Sorry for the confusion. I thought that John Godgame and Alfman being able to play the game meant that it was fixed, but with further testing, I was wrong. Reopen the issue and add the other game to the list.

**Comment by MasonT8198** [comment]
Sometimes they will create custom builds to alleviate this, and it isn't always listed, and they don't say what they changed

**Comment by Triticum0** [comment]
@MasonT8198 John Godgames was using a custom build but alfman didn't so I think it version dependent for flat-out 1 first build version v1.01 was german.

**Comment by mborgerson** [comment]
Let's just track it in #330. Don't need two issues for it.

**Comment by Triticum0** [comment]
What are you taking about I'm talk about Pfifo:423 https://github.com/mborgerson/xemu/blob/a3e507860e831d5a4670d5e8d217d8cdfabb35d6/hw/xbox/nv2a/pfifo.c#L417-L423  
not been fixed after I just retest all the games affected by the issue today.Xemu: ../hw/Xbox/nv2a/pgraph.c:4304: pgraph_render_display_pvideo_overlay: Assertion in_pitch >= in_width * 2 failed occurs on all ISO issue when you eject a disk during the intros so would occur when mason ejected the iso #255 . I do have two of the same issue but, I separated them because the games in #330 crash without user input compared to #255 which affects all game and is a general issue.

**Comment by Triticum0** [comment]
@mborgerson All i'm trying to say is Pfifo:423 is not fixed and it should be reopened or re-reported
