### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [xemu-project/xemu#396]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing xemu on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by GXTX** [comment]
Why flatpak over say something like snap?

**Comment by ghost** [comment]
its already on the aur

**Comment by ghost** [comment]
It will maket he app way more bloaty.
There is already an AUR and a PPA  anyway.

**Comment by j8r** [comment]
Flatpak is another way to package applications. Advantages are easy distribution for all Linuxes, desktop integration with updates, the marketplace and security.

Flatpak/Flathub is more open than snap, which has a closed source marketplace, more universal - even though snap works everywhere.

There are also technical aspects like generally faster start time and no snapd daemon.

---

I'm willing to do the work. @mborgerson has to say he is ok in order to reference it on Flathub.

**Comment by Lunarequest** [comment]
> Flatpak is another way to package applications. Advantages are easy distribution for all Linuxes, desktop integration with updates, the marketplace and security.
> 
> Flatpak/Flathub is more open than snap, which has a closed source marketplace, more universal - even though snap works everywhere.
> 
> There are also technical aspects like generally faster start time and no snapd daemon.
> 
> I'm willing to do the work. @mborgerson has to say he is ok in order to reference it on Flathub.

flatpaks also work on nonsystemd distros unlike snaps

**Comment by C-512L** [comment]
Flatpak does not support libpcap due to sandboxing restrictions, this might be a problem.

**Comment by mborgerson** [comment]
@j8r Thanks for volunteering. If you want to help package a flatpak version (or any other distribution), you are welcome to. It would also be preferable if you'd help maintain the package going forward, as things tend to break and I don't have the bandwidth to babysit myriad packages. Sync with me on the details and if it works well we can update the site with instructions on how to use the distribution.

**Comment by j8r** [comment]
I started to package it, but have been hit by lots of  `undefined reference` to qemu symbols. Here is my WIP branch to reproduce it: https://github.com/j8r/flathub/tree/app.xemu.Xemu#build.
It may be due to the sandbox, or the weird build system: `build.sh` calling `make` calling `meson`. If someone has an idea...

**Comment by j8r** [comment]
Nearly done, got it compiled - the `--enable-lto` was causing issues :slightly_smiling_face:
@mborgerson We'll need some screenshots, in order to pass the linter and also to look nice on the Flathub store.
By the way, in my opinion, having some screenshots in https://xemu.app/ can be welcomed too, to have a quick first glance of how the emulator looks like, in addition to the video. That's even more useful for those en mobile and slow internet.

Then, I'll be able to reference this images from their URLs.

**Comment by j8r** [comment]
I've found a work-around for now by using images generated from YouTube videos.

Now, is there a way to easily get the latest stable release? Unfortunately, in this GitHub repository, the `latest release` should be `latest preview`, because otherwise `latest release` can't point to `xemu-v0.6.1` in https://github.com/mborgerson/xemu/releases :confused:

**Comment by j8r** [comment]
Xemu Flatpak now available at ~https://flathub.org/apps/details/app.xemu.Xemu~ 🎉 

Edit: do not use, will be https://flathub.org/apps/details/app.xemu.xemu

**Comment by mborgerson** [comment]
Great job, @j8r!

Some thoughts:
* Can you change the app name to lowercase `xemu`? This is how it is styled throughout. Not a big deal but it would be nice to be consistent.
* As you suggested, some screenshots on that page would probably be good, but we can update it later.
* Is flathub building from the master branch or does it need to be updated after every release?

**Comment by j8r** [comment]
> Can you change the app name to lowercase xemu? This is how it is styled throughout. Not a big deal but it would be nice to be consistent.

I pushed a commit, I ask for the renaming.

> Is flathub building from the master branch or does it need to be updated after every release?

For now, the version (currently xemu-0.6.1) is set manually. I'd like to set-up a GitHub Action that will update it automatically, by checking everyday for a new release and commit to the repository. For this, I need a way to easily know this.
See https://github.com/stenzek/duckstation/releases for a good example of what I meant by `Pre-release` / `Latest release` .

Using the latest stable release is preferable in my opinion, even more so that xemu has regularly stable releases.
From https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds:

> Flathub only hosts stable application releases, and not development snapshots. Manifests should therefore refer to tarballs or git tags and not the tip of a branch.

However, if the application is only in alpha/beta or has no stable releases (like Flycast), it hasn't been a problem to publish to Flathub.
xemu being can be considered in alpha/beta, it is essentially up to us to decide.

**Comment by mborgerson** [comment]
xemu is still under heavy development, so there isn't a 'stable' release yet. I do occasionally tag a point to mark larger change milestones (xemu-vX.Y.Z) but these are not considered stable. I prefer that people use the latest and greatest release from master branch, at least until xemu reaches v1.0.0 (then we can start calling releases stable).

All other release distributions GitHub, PPA, and the Arch repo (not maintained by me) all release from master branch, so a distribution on flathub should too.

**Comment by j8r** [comment]
Right, fine then, will do.

**Comment by pizzadude** [comment]
On a Thinkpad T580 with Intel HD Graphics, this runs better if I compile it from source. THPS2X runs at 20-30FPS on flatpak build, 50-60FPS compiled from source. Could this be due to seccomp sandboxing in flatpak?

**Comment by j8r** [comment]
This might also be due to LTO being no used, but I doubt it makes such huge difference. If you compile from source it can be unfair compared to using a pre-built package.

You can try to build from source the flatpak too, and compare with that.

**Comment by C-512L** [comment]
> On a Thinkpad T580 with Intel HD Graphics, this runs better if I compile it from source. THPS2X runs at 20-30FPS on flatpak build, 50-60FPS compiled from source. Could this be due to seccomp sandboxing in flatpak?

could it be package not exposing kvm permission?
Xemu uses Qemu which supports kvm but idk if that might be the problem

**Comment by j8r** [comment]
I've tried `--device=kvm`and nothing changed. In fact, hardware acceleration is not supported: #87.

I've no clue then. I was not able to reproduce, since I'm not able to make the emulator work outside Flatpak (was not able to load the iso).

**Comment by j8r** [comment]
Still, it works and can be listed as an installation method on the site.

The best to confirm the slower performance would be to compare the Flatpak package with the [Ubuntu PPA package](https://xemu.app/docs/download/#download-for-linux), because when compiling from source locally optimizations related to the host might be enabled.

If someone else confirm the FPS drop this way, then a mention can be added.

**Comment by j8r** [comment]
So, it was because of my ISO being corrupted somehow. How load a cdrom from the CLI? Using the `-cdrom` option does not seem to work well, I have to use the GUI to load the CD.

Anyway, I haven't noticed a significant drop in performance on my side.

**Comment by dracc** [comment]
> So, it was because of my ISO being corrupted somehow. How load a cdrom from the CLI? Using the `-cdrom` option does not seem to work well, I have to use the GUI to load the CD.
> 
> Anyway, I haven't noticed a significant drop in performance on my side.

Correct switch according to the [docs](https://xemu.app/docs/cli/) would be `-dvd_path=`.

**Comment by mborgerson** [comment]
> Still, it works and can be listed as an installation method on the site.

Shoot me a PR for it and I'll gladly merge it

**Comment by j8r** [comment]
The issue can be closed: the Flatpak is created and instructions are on the site.
