### ISSUE TITLE
Xbox series x controller disconnecting in bluetooth mode

### ISSUE THREAD

**Issue by TailsFan2** [xemu-project/xemu#421]
### Bug Description

Controller disconnects after a few minutes or so of gameplay.

### Expected Behavior

Controller disconnects after a few minutes or so of gameplay.

### xemu Version

Version: 0.5.4-39-gedf3735718
Branch:  master
Commit:  edf373571879bf90baeeb617aa9a0a1cde25097b
Date:    Tue Jul 20 17:39:54 UTC 2021

### System Information

Operating System	Windows 10
Processor	AMD Ryzen 5 4500U with Radeon Graphics            2.38 GHz
Installed RAM	8.00 GB (7.36 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by MasonT8198** [comment]
The Xbox Series X controller disconnecting via bluetooth issue is not actually xemu related, this issue is pretty well known and the bug lies with Microsoft and their lackluster implementation of bluetooth see https://www.google.com/amp/s/amp.reddit.com/r/StarWarsSquadrons/comments/jsfzbx/xbox_series_x_controller_bluetooth_disconnecting/ , https://www.reddit.com/r/ParsecGaming/comments/m9b29v/issue_xbox_series_x_controller_keeps_disconnecting/ , https://answers.microsoft.com/en-us/xbox/forum/all/xbox-series-x-controller-disconnecting-latest/7ad94344-ae1c-4b24-b0d4-063c94a52fe0 . There are a few different solutions, I personally have this issue myself across games and I've throughly researched this. On linux it works perfectly out of the box, however on windows using the xbox wireless adapter seems to fix all issues I've had, but I use wired as I play with multiple people.

Edit: https://www.amazon.com/dp/B00ZB7W4QU/ref=cm_sw_r_cp_api_glt_fabc_R6HDM1E47988XSFMANPF

This one fixed any and all issues I had in games, test environments, etc

**Comment by mborgerson** [comment]
Closing with evidence this is a known issue outside of xemu. If you can get the controller working normally, but only failing with xemu, then please let me know
