### ISSUE TITLE
Widescreen or 720p not available in games

### ISSUE THREAD

**Issue by Bassquake** [xemu-project/xemu#481]
### Bug Description

Widescreen option doesnt seem to show in Black or Virtual Pool. Stuck on 4:3. Setting Xemu to widescreen just stretches it.

### Expected Behavior

Widescreen option should appear in Black's screen options menu. Same for Virtual Pool I think.

### xemu Version

0.6.1-12-ga8c73197da

**Comment by dracc** [comment]
As far as I can tell (judging by the [cover box arts](https://www.mobygames.com/game/xbox/black/cover-art)), Black doesn't support neither Widescreen nor 720p.
Can you please look up whether your physical Xbox presents these options?

**Comment by Bassquake** [comment]
Youre right, Black doesnt support widescreen/720p. I was getting it mixed up with the ps2 version. I will check on a real xbox just to be sure though.

Virtual Pool is however supposed to support 720p as seen here: https://en.everybodywiki.com/List_of_Xbox_games_with_alternate_display_modes

**Comment by dracc** [comment]
FWIW, resolution settings on the Original Xbox are typically not set per game but in your dashboard. I've never played Virtual Pool myself, but I seriously doubt it's any different than most (all?) other games.

**Comment by mborgerson** [comment]
Widescreen/720p can be set through your Xbox dashboard. If you just want higher resolution, I recommend using xemu's render scaling.

xemu's view scaling setting controls how the framebuffer should be displayed, analogous to how a TV connected to a real Xbox would operate. When in standard resolution, games that support 'widescreen', actually support [anamorphic widescreen](https://en.wikipedia.org/wiki/Anamorphic_widescreen). This means the game will render a widescreen image into 4:3 and it's expected to be stretched out by your TV. If the game is not rendering in anamorphic widescreen (because it doesn't support it or hasn't been selected in the dashboard), then selecting widescreen in xemu's scale menu will cause xemu to stretch a 4:3 image to 16:9, and it will appear distorted.
