### ISSUE TITLE
Incorrect video rendering in pre-menu FMV

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#511]
### Title

https://xemu.app/titles/4541007e/#Tiger-Woods-PGA-Tour-06
https://xemu.app/titles/4541003a/#Tiger-Woods-PGA-Tour-2004
NTSC

### Bug Description

Graphical corruption in pre-menu video plaback.

The FMV is rendered on the top part of the screen with a hall of mirrors effect in the lower half (see screenshot). The problem persists throughout the video playback but is resolved at the menu screen, at which point the game appears to be playable.

![Screenshot_20211029_205250](https://user-images.githubusercontent.com/448413/139519301-956cc4fa-c88e-4bc5-ab15-7ae8ec1756f1.png)

### Expected Behavior

The video should play back without corruption

### xemu Version

Version: 0.6.1-27-g42f8873b23
Branch:  master
Commit:  42f8873b23b0f76dca4a7c15c078201263b0464c
Date:    Sat Oct 30 03:42:42 AM UTC 2021

### System Information

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

**Comment by Triticum0** [comment]
NHL 2002 and Pirates: The Legend of Black Kat Also suffer from a similar FMV issues and could be related.

**Comment by Triticum0** [comment]
rendering scale is broken in Tiger Woods PGA Tour 2004, 2005 and 07
![Screenshot from 2021-10-31 19-03-33](https://user-images.githubusercontent.com/71127352/139597810-0e218041-839b-4fff-abb6-431e1ab347ae.png)
This bug also affect the loading screen in Tiger Woods PGA Tour 2004, 2005 and 07 Fixed with #539 
(2004)
![Screenshot from 2021-10-31 19-03-44](https://user-images.githubusercontent.com/71127352/139597906-9891ff18-7e6b-4e08-af24-5f71fdf8dec0.png)
(2005)
![Screenshot from 2021-10-31 22-37-10](https://user-images.githubusercontent.com/71127352/139603505-ae719242-e471-47ae-9a99-209e3864ffae.png)

**Comment by Triticum0** [comment]
Also Testing Tiger Woods PGA Tour 2004 in crashes with a segmentation fault after you finish the mandatory tutorial skipping the trick shot section.

**Comment by Triticum0** [comment]
The same bug also affect AND 1 Streetball but the FVM doesn't render

**Comment by Triticum0** [comment]
on windows this game still crashes

**Comment by Triticum0** [comment]
#539 fixed both games as well as And1 Streetball, Xyanide, Robin Hood Defender Of The Crown and Without warnings fmv. it should probably fix Prisoner of War fmv's but will need to test to make sure

**Comment by Triticum0** [comment]
This also fixed Prisoner of war FMV's Which caused a memory leak

**Comment by Triticum0** [comment]
It Does'nt =(
