### ISSUE TITLE
Nba jam menu Only renders the background

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#670]
### Title

https://xemu.app/titles/41430013/#NBA-Jam

### Bug Description

The text and charterers  on the menu screen are missing

xemu:
![Screenshot from 2021-11-02 22-48-01](https://user-images.githubusercontent.com/71127352/141383159-517f2d88-1f77-4cdd-b5e9-e6b9758cc28f.png)

xemu:
![Screenshot from 2021-11-02 22-48-27](https://user-images.githubusercontent.com/71127352/141383256-5a0d826a-32e4-4ad8-9d59-3d530d54fdde.png)

xemu:
![Screenshot from 2021-11-02 22-48-31](https://user-images.githubusercontent.com/71127352/141383263-6c3a3dc9-a4d9-41ca-8b81-edeced543d21.png)

### Expected Behavior

xbox:
![Screenshot from 2021-11-11 23-52-06](https://user-images.githubusercontent.com/71127352/141385456-3669e142-d431-4c3a-840d-55b3bc44f0d4.png)

xbox:
![Screenshot from 2021-11-11 23-52-14](https://user-images.githubusercontent.com/71127352/141385470-337b8c37-e27a-4502-a47d-6ecb2af7239f.png)

xbox:
![Screenshot from 2021-11-11 23-52-35](https://user-images.githubusercontent.com/71127352/141385486-8ef52b53-da25-49bd-95bb-c5bfb37a8625.png)

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: N/A

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

Interesting tidbit the same bug on Nba jam also occurs on [pcsx2 ](https://github.com/PCSX2/pcsx2/issues/5262) 
Seem to be an ordering problem.

**Comment by abaire** [comment]
If you're up to it, I'd be very interested in what happens if you enable [DEBUG_NV2A_REG](https://github.com/mborgerson/xemu/blob/6b821d2062f28d8b04c7e02447ed066b50936eea/hw/xbox/nv2a/debug.h#L39) and log the output. Specifically any line that include `PVIDEO` would be of interest.

It's possible that NBA Jam uses a color key that has alpha (which is why it wasn't fixed along with SeaBlade by #669) or that it's using an entirely different mechanism to render the background.

**Comment by Triticum0** [comment]
I try to but i did get any output log on window do I need to enable [this](https://github.com/mborgerson/xemu/blob/6b821d2062f28d8b04c7e02447ed066b50936eea/hw/xbox/nv2a/debug.h#L32) as well for it to work?

**Comment by abaire** [comment]
Oh, yes, sorry! You do need both.

**Comment by Triticum0** [comment]
Here's the log
[log.zip](https://github.com/mborgerson/xemu/files/7929358/log.zip)

**Comment by Triticum0** [comment]
@abaire I'm not sure where Xemu stores the log or how to output the terminal to a log. So it is not all the terminal output due to the terminal line limit. My anti-virus software on windows was giving me problems, so I had to reinstall Ubuntu to do the testing. So it took a while to do the testing.

**Comment by abaire** [comment]
@Triticum0 no problem, I appreciate your help!

I don't see any pvideo invocations in that log so it may be that NBA Jam is actually not the same issue as SeaBlade (which was a problem with a particular mechanism for doing color keyed videos).

FYI if you're testing on Linux, the easiest way to capture the log is to run from terminal and pipe it to a file: E.g., if you're in the "dist" directory after building:
`./xemu.app -dvd_path path_to_the_xiso_to_test > log.txt`

In this case I'm most interested in the pvideo lines so you could even pipe through grep to limit the amount of data:
`./xemu.app -dvd_path path_to_the_xiso_to_test | grep -i "PVIDEO" > log.txt`

**Comment by Triticum0** [comment]
@abaire I tried that and it said (bash: ./xemu.app: No such file or directory)  do I need the make the directory first to do it. I not very knowable in how Linux terminal works so might be a dumb question.

**Comment by Triticum0** [comment]
It seem to create a log so i worked but not sure why it gave a error

**Comment by Triticum0** [comment]
I've never use terminal to mount ISO before so i not sure what I'm doing wrong to not get an log. Are you meant to go into the .ini file to get the log to work?

**Comment by abaire** [comment]
> @abaire I tried that and it said (bash: ./xemu.app: No such file or directory) do I need the make the directory first to do it. I not very knowable in how Linux terminal works so might be a dumb question.

Yup, you need to `cd` into whatever directory you have xemu in.

I was on macOS when I wrote those instructions and erroneously put ".app" on the end, you're probably already doing the right thing and just need `./xemu` without the `.app` suffix (which is specific to macOS app bundles) - sorry about that!

On linux you want something like:
`./xemu -dvd_path path_to_the_xiso_to_test > log.txt`

after `cd`-ing into the `xemu/dist` directory.

**Comment by Triticum0** [comment]
@abaire I got it working just now. Thank you for the help. Removing .app did the trick. I will send the log soon. Also will do a log for some of the other issues, that I created, but I'm not sure how pgraph.c#L27 and pgraph.c#L28 to 1 changes the output in any way, same with DEBUG_NV2A_REG. They don't seem different from just enabling debug. I do get other values when I use nv2a: Make nv2a_dprintf toggleable pr and untoggle log output, but I might just not have enough to tell the difference. I Just want to make sure I'm doing this correctly, so the logs are useful. Please say what log you think will be useful for the 54 issues I created, and I will get on with making logs for them all so they can get solved.

**Comment by Triticum0** [comment]
Here the full log file
[log.zip](https://github.com/mborgerson/xemu/files/7930174/log.zip)

**Comment by abaire** [comment]
> @abaire I got it working just now. Thank you for the help. Removing .app did the trick. I will send the log soon. Also will do a log for some of the other issues, that I created, but I'm not sure how pgraph.c#L27 and pgraph.c#L28 to 1 changes the output in any way, same with DEBUG_NV2A_REG. They don't seem different from just enabling debug. I do get other values when I use nv2a: Make nv2a_dprintf toggleable pr and untoggle log output, but I might just not have enough to tell the difference. I Just want to make sure I'm doing this correctly, so the logs are useful. Please say what log you think will be useful for the 54 issues I created, and I will get on with making logs for them all so they can get solved.

The `DBG_SURFACES` defines are only useful for a very particular class of bugs. `DEBUG_NV2A_REG` is also only interesting for a subset of bugs, though it's broader than the surface stuff and is specifically interesting for things like SeaBlade that use the pvideo subsystem. I wouldn't bother enabling the two in pgraph.c, but I would expect DEBUG_NV2A_REG to print out a bunch more data than `DEBUG_NV2A` alone (though they'll all start with `nv2a:` so it might not be immediately obvious if you don't know what to look for).

The log you attached is exactly what I was looking for, the lines like `nv2a: PMC: read [0] -> 0x2a000a3` mean that `DEBUG_NV2A_REG` is correctly enabled.

I still don't see any PVIDEO manipulation though, so I'm pretty confident now that the failure for this game is something different from SeaBlade and will need to be debugged some more. I'll take a deeper look at the log in the coming days and see if there's anything obviously wrong, otherwise I'll see if I can find it cheap on eBay :)

At the moment I wouldn't bother doing logs for all 54 issues, I've ordered a number of the games you've reported on and it's probably faster for me to debug directly where I can actually see the data on top of the pgraph logs. It won't hurt to have logs, but they're not always directly useful and I don't want to waste your time! If you don't mind, I'll tag you when I come across bugs where a log would be helpful.

**Comment by abaire** [comment]
Looking at the log in more detail, I see a lot of unhandled commands for `0x1e90` and `0x1e80` which may be important. They're nestled in between modifications to the vertex shader constants and the vertex shader itself so I'd guess they're somehow related to vertex shading?

**Comment by Triticum0** [comment]
This is mostly fixed with #1080

**Comment by Triticum0** [comment]
@abaire You fixed the menu issue It doesn't happen in latest build

**Comment by Triticum0** [comment]
But the shadows are still broken look like vsh issue

https://user-images.githubusercontent.com/71127352/175770540-f1ec04ad-1ed6-4639-8256-03681debff9d.mp4
