### ISSUE TITLE
Half-Life 2: Assertion failed!

### ISSUE THREAD

**Issue by kibmcz** [xemu-project/xemu#730]
### Title

https://xemu.app/titles/45410091/#Half-Life-2

EA-145

### Bug Description

Game triggers assert on scenes when certain in game events are active.

Steps to reproduce this issue:
1. Launch Game
2. Start New game
3. Play Point Insertion until you are at where the Combine asks you to pick up the can.

![xemu_2022-02-08_22-30-13](https://user-images.githubusercontent.com/857986/153122899-439d01cc-490f-4183-97ec-62bac8156c70.png)

### Expected Behavior

Ability to progress the game as it plays on the actual system.

### xemu Version

0.6.2-64-g758e36d398

### System Information

OS: Windows 11
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
GPU: Nvidia GeForce GTX 1050

### Additional Context

Same assertion continues on into the game  (tracked it as far as Red Letter Day) and ony seems to happen when certain NPC's are active. Seems to not trigger when just kleiner and alyx are in the lab but as soon as barney walks into room it immediately trigers.

**Comment by abaire** [comment]
Testing this on Linux, it dies with the same (unfortunately not very useful) assertion during/just on completion of the loading after jumping out the window post interrogation-scene.

The actual GL error is `GL_INVALID_FRAMEBUFFER_OPERATION` with the underlying reason:

`GLDBG[ERROR][HIGH]> GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.`

Adding some debug code for that, it looks like it's specifically `GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT` which `is returned if the framebuffer does not have at least one image attached to it`

Looks like it's triggered when handling the `NV097_CLEAR_SURFACE[0] 0xf0` (clear color buffer) when the loading is completed (specifically the `glClear(gl_mask)` call). I'm suspicious of the [fixme inside of `pgraph_update_surface`](https://github.com/mborgerson/xemu/blob/8919bae31156a8534d529be0012670020fcd5704/hw/xbox/nv2a/pgraph.c#L4443) where `color_write` and `zeta_write` are both disabled, leading to the surfaces being unbound but nothing being re-bound.

**Comment by abaire** [comment]
As @Triticum0 pointed out on the fix PR, this may be related to several other bugs:
#288 #140 #387 should be re-tested once this bug is closed.
