### ISSUE TITLE
Oddworld: Stranger's Wrath - Foggy graphic

### ISSUE THREAD

**Issue by LoStraniero91** [xemu-project/xemu#769]
### Title

https://xemu.app/titles/4541006d/#Oddworld:-Stranger's-Wrath

Oddworld: Stranger's Wrath
EA-109 [4541006d]

### Bug Description

Graphic in game is totally foggy, covering everything but some minor elements like grass.

Step to reproduce this issue:

1. Launch the game
2. Select New Game
3. Watch the first cutscene and then you'll begin the tutorial, where you will not be able to make out almost anything.

![Immagine](https://user-images.githubusercontent.com/29802222/158276326-9a377835-0b07-46c4-9281-41d0bb134f94.png)
In this screenshot I've managed to get to town since I know the game like the back of my hand, but it would be still impossible to play in latter levels.

### Expected Behavior

The graphic should not be covered with this fog wall.

![image](https://user-images.githubusercontent.com/29802222/158276678-bcdd37e1-e7b7-45f0-b9ff-29965a5f5d90.png)
Screenshot taken from a YouTube gameplay, but this is the correct behavior.

### xemu Version

v0.6.2-80-g5d02cdf512

Never worked in any previous version.

### System Information

OS: Windows 10
CPU: Intel i9-9900k
GPU: Nvidia RTX 2080 Ti
GPU Driver: 511.79

**Comment by abaire** [comment]
The Need for Speed games had similar behavior that will be fixed when #677 is merged, might be interesting to test with that.

**Comment by Fabxx** [comment]
> The Need for Speed games had similar behavior that will be fixed when #677 is merged, might be interesting to test with that.

i tested the game with that PR, it looks like this:
![image](https://user-images.githubusercontent.com/30447649/158428870-c29b2d2e-4a18-4928-9f61-826fac2e91c1.png)

Apparently this might not be fog related but there's something else

**Comment by abaire** [comment]
Pgraph trace for the beginning of the first level:
[oddworld_sw_fog.txt](https://github.com/mborgerson/xemu/files/8289851/oddworld_sw_fog.txt)

Looking at a renderdoc capture, it seems like it builds up the scene mostly fine (renders the character model):
![osw_111402](https://user-images.githubusercontent.com/448413/158880577-a52f7727-b8db-434d-af61-c602daf33e03.png)

Then it renders something very interesting (look with the alpha channel disabled, to me this looks like a depth map rendered as a texture)
![osw_111737](https://user-images.githubusercontent.com/448413/158880702-73856516-ff69-481a-9dc7-f0fd7e1123e2.png)

Then it appears to clear the framebuffer to the blue-grey color w/ zero alpha, which is itself interesting since I don't see `SET_COLOR_CLEAR_VALUE` setting a value that seems correct) 
![osw_112684](https://user-images.githubusercontent.com/448413/158880920-4dd710b8-40e7-4e86-89ca-39b9b9f1b5be.png)


Also interesting, xemu is using a geometry shader for this frame, looks like `PRIM_TYPE_QUADS` w/ `POLY_MODE_FILL`

The pixel shader is one stage with 3 textures. The first texture is the framebuffer so far, the second looks like the interesting depth-map, and the third is a 256x2 stepped gradient:
![texsamp2](https://user-images.githubusercontent.com/448413/158882319-ca7f3ffb-4e1a-493b-bf8c-6073697e6e80.png)

Relevant combiner code:
```
pT0.xy = texScale0 * pT0.xy;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
pT1.xy = texScale1 * pT1.xy;
vec4 t1 = textureProj(texSamp1, pT1.xyw);
vec4 t2 = texture(texSamp2, t1.ar);
vec4 t3 = vec4(0.0); /* PS_TEXTUREMODES_NONE */
vec4 r0;
r0.a = t0.a;
// Stage 0
ab.a = clamp(((t2.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))), -1.0, 1.0);
r0.a = ab.a;
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(t0.rgb, 0.0)), vec3(max(c0_8.rgb, 0.0)), vec3(max(t2.aaa, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

It looks like the depth texture's alpha and red channel are used as a lookup into the stepped gradient, where the alpha channel is then used to decide between c0_8 (the blue-grey fog color, `SET_SPECULAR_FOG_FACTOR = 0xFF688098`) and the original framebuffer content. It would naively appear that this goes wrong and t2.a is always 1, leading to the blue-grey color being used for everything. Looking at the t2 texture, the alpha appears to be 1 everywhere, which seems very suspicious. Setting the shader to use the red channel produces output that looks more reasonable, but the final combiner explicitly uses `Tex2 Alpha`.

The interesting draw probably around line 28779 of the pgraph trace (which configures alpha ICW to be Tex2's blue channel and then sets the c0_8 factor to the fog color).

**Comment by abaire** [comment]
The gradient image that is used to select gradient uses the `SZ_R8B8` format which I have not tested in the past, that seems like a good place to start.

Confirmed that the handling of that image appears to depart substantially from HW.

**Comment by LoStraniero91** [comment]
![image](https://user-images.githubusercontent.com/29802222/158995529-8936cfb0-e586-4a97-8536-d9c4249dcb5a.png)

Very nice job indeed, I'm gonna play a bit with this build and report other findings.
