### ISSUE TITLE
007 - Nightfire : The European version of the game freezes when starting the tutorial

### ISSUE THREAD

**Issue by JlnGlbrt** [xemu-project/xemu#809]
### Title

https://xemu.app/titles/45410026/#007-Nightfire

### Bug Description

To reproduce this issue : 

1. Change the language setting to 'French' in the eeprom file
2. Launch the European version of the game [007 - Nightfire (Europe) (En,Fr,De,Es,It,Nl,Sv).iso]

### Expected Behavior

The game starts normally but freezes when loading the tutorial. This is not the case on the US version. This must be due to the loading of the game's translation files.

### xemu Version

v0.6.2-88-g6e1969001e

### System Information

OS : Windows 10
CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
GPU : NVIDIA GTX 1650

### Additional Context

I am French so I wanted to launch the game in French. That's why I modified the eeprom file and changed the language setting to 'French'. The US version works perfectly so I believe the problem comes from the European version.

**Comment by Xario123** [comment]
I am French and i have the same problem. Works perfectly with the English version of the game but the European version with the French language selected, the game crashes when starting the tutorial.

**Comment by Xario123** [comment]
I found a solution. You have to load a PAL EEPROM in XEMU and the game starts in French with the European version. You can try this one: 
[eeprom_pal.zip](https://github.com/mborgerson/xemu/files/10012996/eeprom_pal.zip)

I edited it with "XboxEepromEditor" to convert it to PAL. Be careful, you have to keep an NTSC EEPROM otherwise you will probably have problems with some games that worked before, to see.

**Comment by JlnGlbrt** [comment]
Hi Xario, I tried your solution and it works perfectly!
Thank you!!!
