### ISSUE TITLE
Oddworld: Stranger's Wrath - Black/green splotches on characters

### ISSUE THREAD

**Issue by LoStraniero91** [xemu-project/xemu#851]
### Title

https://xemu.app/titles/4541006d/#Oddworld:-Stranger's-Wrath

Oddworld: Stranger's Wrath
EA-109 [4541006d]

### Bug Description

Characters don't look correct: they have black/green splotches depending on position/lighting.

Step to reproduce this issue:

1. Launch the game
2. Select New Game/Load any game
3. Admire the broken characters.

![image](https://user-images.githubusercontent.com/29802222/165077674-b35e88f9-505e-4ffa-927f-01de0bc7a56c.png)

### Expected Behavior

Characters shouldn't look like that. Attaching the same screenshot of my previous reported issue, it works just fine to see how characters should be (no black splotches anywhere).

![image](https://user-images.githubusercontent.com/29802222/165077813-1de79781-9ebf-4174-ae37-ee56f3a98768.png)

### xemu Version

v0.6.3

Never worked in any previous version.

### System Information

OS: Windows 10
CPU: Intel i9-9900k
GPU: Nvidia RTX 2080 Ti
GPU Driver: 512.15

**Comment by abaire** [comment]
There is one draw that applies the corrupted textures to the model. Input textures use `NV097_SET_TEXTURE_FORMAT_COLOR_SZ_X8R8G8B8` with an alpha discard set to `0.0039216`.

~~I'm suspicious that X8 either implies actual pass through of the existing state of the surface or sets it to some alpha value that xemu isn't matching, causing the texture to be applied places it shouldn't be (or not applied places it should be).~~ This is incorrect: a) There's already a pgraph test confirming that this format works fine and sets alpha to 1; b) the final combiner forces alpha to 1 anyway, which seems odd given the alpha ref.

The texture that is being applied (t3) is a cubemap
Pixel shader is also using DOTPRODUCT mode

```
pT0.xy = texScale0 * pT0.xy;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
/* PS_TEXTUREMODES_DOTPRODUCT */
float dot1 = dot(pT1.xyz, dotmap_minus1_to_1_d3d(t0.rgb));
vec4 t1 = vec4(0.0);
/* PS_TEXTUREMODES_DOTPRODUCT */
float dot2 = dot(pT2.xyz, dotmap_minus1_to_1_d3d(t0.rgb));
vec4 t2 = vec4(0.0);
/* PS_TEXTUREMODES_DOT_STR_CUBE */
float dot3 = dot(pT3.xyz, dotmap_minus1_to_1_d3d(t0.rgb));
vec4 t3 = texture(texSamp3, vec3(dot1, dot2, dot3));
vec4 r0;
r0.a = t0.a;
// Stage 0
ab.rgb = clamp(vec3((t3.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))), -1.0, 1.0);
ab.a = clamp(((t3.a * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))), -1.0, 1.0);
r0.rgb = ab.rgb;
r0.a = ab.a;
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(r0.rgb, 0.0)), vec3(max(c0_8.rgb, 0.0)), vec3(max(v0.aaa, 0.0)));
fragColor.a = (1.0 - clamp(vec4(0.0).b, 0.0, 1.0));
if (!(fragColor.a >= alphaRef)) discard;
```


Forcing v0.a to 1.0 preserves the (correct looking but very bright) original texture. Setting it to 0.0 produces the blacked out overlay.


Relevant pgraph setup for the draw:
```
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_ADDRESS[0]<0x1B08> (0x10101 {U:Wrap, V:Wrap, P:Wrap})
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_ADDRESS[1]<0x1B48> (0x10101 {U:Wrap, V:Wrap, P:Wrap})
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_ADDRESS[2]<0x1B88> (0x10101 {U:Wrap, V:Wrap, P:Wrap})
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_SHADER_STAGE_PROGRAM<0x1E70> (0x74621 {0:2D_PROJECTIVE, 1:DOT_PRODUCT, 2:DOT_PRODUCT, 3:DOT_STR_CUBE})
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_ADDRESS[3]<0x1BC8> (0x50505 {U:Clamp_OGL, V:Clamp_OGL, P:Clamp_OGL})
```

The OGL clamping may or may not be important, xemu has https://github.com/mborgerson/xemu/blob/7d6da227ba3b224647e35d2385419a3bec25a3b3/hw/xbox/nv2a/pgraph.c#L118
for that mode

**Comment by abaire** [comment]
I previously wrote a test for clamping behavior that shows the difference:

xemu results from a close-to-master build:
![Screenshot_20220531_132600](https://user-images.githubusercontent.com/448413/171278683-b2908739-5ff3-4764-8660-7c30b8002fb9.png)


HW results of 
![HW](https://raw.githubusercontent.com/abaire/nxdk_pgraph_tests_golden_results/main/Texture_border/2D.png)

I'm suspicious that the clamping difference (mixing the edge texel with the border color) may be important in this case.


UPDATE: Maybe not that important: `nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_FORMAT[3]<0x1BC4> (0x3310725 {DMA_A, ENABLE_CUBEMAP, BORDER_SOURCE_TEXTURE, SZ_X8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:8, BaseSizeV:8, BaseSizeP:1})` the border source is not set to the border color.

**Comment by abaire** [comment]
~~The `DOT_STR_CUBE` shader in xemu produces different results from [HW](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_cubemap) in my [test case](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_cubemap_tests.cpp).~~
Turns out that the difference was around using the fixed function pipeline versus programmable. xemu (erroneously?) accepts 4-component texture coordinates in fixed function, hardware looks like it ignores the `r` and `q` params, which led to my test being invalid. I switched to a programmable vertex shader that explicitly handles all 4 coords and xemu mostly matches hardware, and in the actual case being used by Oddworld, exactly matches.

**Comment by abaire** [comment]
And digging in again, the cubemap is a `BORDER_SOURCE_TEXTURE` which means #1004 is potentially (I think likely) the cause. Looking at the cubemap texture in renderdoc, it's offset by a 4 texel border which is black. This matches neatly with the expected behavior for `BORDER_SOURCE_TEXTURE` mode textures, the hardware expects a 4 pixel border which is ignored except in the case of negative texcoords (or coords > 1.0). Given that this is a cubemap I don't think it's possible to get out of range texcoords so the lack of border handling means that they end up referencing the border area which happens to be all black.

**Comment by abaire** [comment]
Confirmed that #1004 is the cause and put together a fix.
