### ISSUE TITLE
Xemu on ARM

### ISSUE THREAD

**Issue by ConLenov** [xemu-project/xemu#857]
### Feature Request

Hello. I have a question: does Xemu support ARM? 

It would be nice to play Windows 11 games on a tablet via Xemu. OS: Android and ARM-Linux

**Comment by mborgerson** [comment]
xemu has arm builds for macos and Ubuntu, but not for Windows

**Comment by mborgerson** [comment]
Dup #791

**Comment by ConLenov** [comment]
@[mborgerson](https://github.com/mborgerson) That is, I will be able to play XboxOriginal - games on Arm - devices (tablets, Orange Pi)?

**Comment by Wooty-B** [comment]
@ConLenov Yes, I currently am using an ARM64 developer board with an AMD GPU and Xemu runs, albeit with some sluggishness. Comparing my board (2.2Ghz A72) with an Apple M1 chip, it appears performance gains decrease exponentially probably due to the emulation required from x86 -> arm64. However the latter is just my speculation.

On a perfect day with great ARM hardware expect anywhere from 10-30fps on well supported titles, (which is incredible!) and under 5-10fps in many other titles. I am trying not to be pessimistic, as I believe Xemu on ARM chipsets will become better supported, or will help another fork/project with an engine designed for cross compatibility.
