### ISSUE TITLE
Support attaching Xbox Memory Units (XMU)

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#90]
I'm unable to attach the XMU to the "hub" the controller is supposed to provide. I don't believe the controller is acting like a hub here.

![xmu](https://user-images.githubusercontent.com/858612/100552282-2c7d8f80-3254-11eb-945e-f2d566d5c033.png)

Also cannot connect multiple XMUs to the same port.

![image](https://user-images.githubusercontent.com/858612/100552356-c6453c80-3254-11eb-9356-0fc126209e08.png)

**Comment by Ryzee119** [comment]
I believe this can be closed now from https://github.com/mborgerson/xemu/pull/550
xemu supports the internal daughter board and now the internal usb hubs within the controllers. You can connect and usb storage device on port 1.x.1(or .2) where x is 3,4,1,2 for player 1,2,3,4 respectively. 

I suppose there is no gui elemted yet to do this, so that issue is still present

**Comment by mborgerson** [comment]
Sounds good. This feature is [documented here](https://xemu.app/docs/xmus/), so let's consider the UI for this a separate problem to solve
