### ISSUE TITLE
Splinter cell: Broken loading screen image

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#937]
### Title

https://xemu.app/titles/5553000c/#Tom-Clancy-s-Splinter-Cell

### Bug Description

Steps to reproduce:
load a level
press start
a corrupted image appears for a second

![image](https://user-images.githubusercontent.com/30447649/169357324-e45a4cce-bb34-414a-9a4b-eff7de495107.png)

### Expected Behavior

There shouldn't be a corrupted image on the screen

### xemu Version

0.7.15

### System Information

CPU:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
OS Platform:  Linux
OS Version:   Manjaro Linux
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.68.02
Shader:       4.00 NVIDIA via Cg compiler

**Comment by abaire** [comment]
It actually is cross faded with the loading screen as well, the screenshot above shows up after the loading screen is entirely faded out. You can capture this in renderdoc by triggering a 10 frame capture inside `pgraph_surface_invalidate` when it does an unbind of the zeta surface (with PR #935 merged https://github.com/mborgerson/xemu/commit/eb9bae8d2608390280a0e87ef52f1e74354a7673); it's otherwise very difficult to get the timing right as it doesn't crossfade immediately when pressing start on the loading screen.

Looking at the pgraph log for the game, the texture is 0x31b8000 (640x480 linear ARGB).
I don't see any pgraph-related writes to this address, even watching from initial boot of the game. It's possible that this memory is being accessed by the CPU before use (since it's never a target surface I don't think the `pgraph_surface_access_callback` gets invoked so there's no trace message to confirm).

[sc_corrupt_prior_to_start.txt](https://github.com/mborgerson/xemu/files/8732409/sc_corrupt_prior_to_start.txt)
