### ISSUE TITLE
Generated shaders and config file errors with comma separated float locale

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#975]
### Title

https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2

### Bug Description

After getting in game and having the "GO!" signal, xemu crashes with a SIGABORT and gives this shader log:

[shader log.txt](https://github.com/mborgerson/xemu/files/8777893/shader.log.txt)

GDB stack trace:
[GDB stack.txt](https://github.com/mborgerson/xemu/files/8777897/GDB.stack.txt)

### Expected Behavior

The shader should not fail to compile and you should be able to continue the race.

### xemu Version

0.7.21

### System Information

CPU:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
OS Platform:  Linux
OS Version:   Manjaro Linux
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.73.05
Shader:       4.00 NVIDIA via Cg compiler

**Comment by mborgerson** [comment]
Apparent locale string format issue https://github.com/mborgerson/xemu/blob/0cdcdde70c13f6cf3ed09aca29185ed790b22485/hw/xbox/nv2a/shaders.c#L685

**Comment by abaire** [comment]
Hey @revix-0 can you update the title of this bug so it's clear you're using a locale where floating points use commas instead of periods (I assume Italian, but also assume this will happen in any location where 1/2 = "0,5")?

Maybe "Shader compilation error with comma separated float locale"? It'd be good to have a more generic name since #983 looked like the same issue and was presumably not PGR2

**Comment by jeep0621** [comment]
happened to me with pgr2 but also other games : dead or alive 3 and ultimate, burnout 3 and revenge, ninja gaiden black, while some other games didn t crash
