### ISSUE TITLE
various games crashes newly on 0.7.2 nv2a locale related?

### ISSUE THREAD

**Issue by jeep0621** [xemu-project/xemu#983]
### Bug Description

nv2a: vertex shader compilation failed: 0(169) : error C1115: unable to find compatible overloaded function "sqrt(int, int, float, float)"
0(169) : error C0158: invalid digit '9' in octal constant
0(170) : error C1115: unable to find compatible overloaded function "min(float, int, int, float)"

gives many games to crash on linux xemu 0.7.2
workimg with previous versions

### Expected Behavior

games mudt not crash

### xemu Version

0.7.2

### System Information

os linux lmde5
i5 12600k
gtx 1650
32gb ram

**Comment by Fabxx** [comment]
can you retry with the lastes version 0.7.21? this is pretty outdated

**Comment by jeep0621** [comment]
i am on flatpak and no 0.7.21 yet, i'll wait
thanks for your help

**Comment by abaire** [comment]
This sounds like a dup of #975, the issue is probably the number locale (I assume you're using a system locale that uses decimal numbers w/ commas, e.g., 1/2 = "0,5" rather than the English "0.5". 

7.21 probably won't fix this for you, but overriding the locale for xemu might, if that's an option.

**Comment by jeep0621** [comment]
you must be right
i noticed the xemu.toml file had a problem with a coma instead of a point on the volume limit number, causing xemu not opening:
error parsing config file at line 16 column 17error while parsing key value repair expected a comment or a white space saw "," please fix he error or delete the file to continue

i just changed the , for a . in thi file and xemu opened, but should be related. my system locale is french but my keyboard is italian locale if it helps

how can i override the locale for xemu please?
thamks

**Comment by abaire** [comment]
> you must be right i noticed the xemu.toml file had a problem with a coma instead of a point on the volume limit number, causing xemu not opening: error parsing config file at line 16 column 17error while parsing key value repair expected a comment or a white space saw "," please fix he error or delete the file to continue
> 
> i just changed the , for a . in thi file and xemu opened, but should be related. my system locale is french but my keyboard is italian locale if it helps

It's only the system (numeric) locale that matters, you should be able to use whatever keyboard layout you prefer.

> 
> how can i override the locale for xemu please? thamks

It depends on your OS, on Linux you should be able to set the `LC_NUMERIC` environment variable, but you'll need to have an appropriate locale installed (en_US or en_GB would work). I have not tried on other systems, but if you search for something like "windows change locale for single program" you should be able to find something (I see a few results, but since I've never tested them and don't know what kind of problems they might cause I won't recommend any)


Also, can you close this issue again since it appears to be a dup of #975? We only need one issue to track the problem (otherwise it's hard to keep track and close them all when it gets fixed). If you have other questions you can either ask on Discord or add them to #975.
